version: '2'
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
services:
  elasticsearch1:
    mem_limit: 1000000000
    cap_add:
    - IPC_LOCK
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      bootstrap.memory_lock: 'true'
      cluster.name: docker-cluster
      xpack.security.enabled: 'false'
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - esdata1:/usr/share/elasticsearch/data
    ports:
    - 9200:9200/tcp
  elasticsearch2:
    mem_limit: 1000000000
    cap_add:
    - IPC_LOCK
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      bootstrap.memory_lock: 'true'
      cluster.name: docker-cluster
      discovery.zen.ping.unicast.hosts: elasticsearch1
      xpack.security.enabled: 'false'
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        hard: 65536
        soft: 65536
    volumes:
    - esdata2:/usr/share/elasticsearch/data
